### PR TITLE
Update German translation

### PR DESCRIPTION
**Pull request by WebSnke**
## Description: Update German translation

Please include a summary of the changes and the related issue.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style (formatting, new lines, etc.)
- [ ] Refactoring (no functional changes, renaming)
- [x] Other (describe the changes): Translation

## Checklist:

- [x] My code follows the style and architecture of the project
- [x] I have performed a self-review of my code
- [x] I have tested the app on an actual Android device and everything works as expected
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] New and existing tests pass locally with my changes

### CODE REVIEW

**Comment by mhss1** [comment]
Make sure you have the latest version of the file. there is a new "recurring" string in the new version that does not exist in yours

**Comment by mhss1** [comment]
You can get the new version by going to your MyBrain fork and click "Sync Fork"

**Comment by WebSnke** [comment]
@mhss1 
I would also like to add a translation for "recurring" but I don't really know what it means in this context.
Could you maybe explain it to me?

**Comment by mhss1** [comment]
@WebSnke a recurring task. A task that repeats daily, weekly, or monthly

**Comment by WebSnke** [comment]
> @WebSnke a recurring task. A task that repeats daily, weekly, or monthly

Thanks. I just added the translation for it.

**Comment by mhss1** [comment]
Thanks for the contribution

**Pull request merged**
