### PR TITLE
added hindi translation

### PR DESCRIPTION
**Pull request by dubeyanant**
## Description

Added Hindi language translation to the app.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style and architecture of the project
- [x] I have performed a self-review of my code
- [x] I have tested the app on an actual Android device and everything works as expected
- [x] My changes generate no new warnings or errors
- [x] New and existing tests pass locally with my changes

### CODE REVIEW

**Comment by mhss1** [comment]
I'm adding something currently to the app and I will most likely finish it tomorrow that will need more strings. So I will wait until I finish it then merge the PR to make sure all strings are translated.

**Comment by dubeyanant** [comment]
Sure.

**Comment by dubeyanant** [comment]
Ping me when you are done.

**Comment by mhss1** [comment]
These are the strings : 
```
    <string name="app_font">App Font</string>
    <string name="font_system_default">System default</string>
    <string name="delete_event">Delete event</string>
    <string name="location">Location</string>
    <string name="do_not_repeat">Do not repeat</string>
    <string name="every_day">Every day</string>
    <string name="every_week">Every week</string>
    <string name="every_month">Every month</string>
    <string name="every_year">Every year</string>
    <string name="error_future_event">Event should not be in the past</string>
    <string name="delete_event_confirmation_title">Delete Event?</string>
    <string name="delete_event_confirmation_message">Are you sure you want do delete this event?</string>
```

**Comment by dubeyanant** [comment]
Can you commit these changes to Strings.xml file?

**Comment by mhss1** [comment]
I pushed the commit

**Pull request merged**
